name: Make npm prerelease

on:
    push:
        branches:
            - actions

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Setup Node.js
              uses: epeli/prerelease@master
